### ISSUE TITLE
About reading local nfo

### ISSUE THREAD

**Issue by 666wcy** [libDrive/libDrive#10]
First of all, thank the author for his good program.

Reading local NFO is a good way to get posters. Reading the files scraped by tiny media manager and then displaying the poster wall is also a good choice

I hope to come up with such a way to obtain film and television information in the future

**Comment by eliasbenb** [comment]
This is a great idea, but the problem is that this would create the need for 2 extra requests per file, 1 for scanning the directory of the folder, and a second to read the nfo file. Which in my opinion isn't worth implementing for a niche group of users, like yourself.

Also, libDrive doesn't generate nfo files, so I don't see myself implementing this.

Thank you for the suggestion though and your interest in this project!

**Comment by eliasbenb** [comment]
Since the issue is stale, I'll be closing it now.
