### ISSUE TITLE
Video load failed

### ISSUE THREAD

**Issue by Naim120** [libDrive/libDrive#22]
Hello again. Sorry to disturb u again, but sometimes its showing "Video load failed" and can't play the video. Can u help plss??

**Comment by killerlearner** [comment]
Try transcoding = true in config, It will add more video support as given in wiki!

**Comment by Naim120** [comment]
Tried. But, Still showing video load failed

**Comment by flixdrive9** [comment]
Are your videos transcoded?

**Comment by eliasbenb** [comment]
This is not a libDrive issue, this is an issue with your browser. Browsers are unable to play most video codecs because of copyright issues.

You can play the video using an external player to avoid the issue, or as @killerlearner said, you can enable transcoding, but this still doesn't guarantee playback.
